version: 0.2
env:
  variables:
    BUILD_ENV: prod

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm ci
      - npm install -g @angular/cli
  pre_build:
    on-failure: ABORT
    commands:
      - echo Linting project...
      - ng lint
      - echo Testing project...
      - npm test
  build:
    commands:
      - echo Building project...
      - ng build --${BUILD_ENV}
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - dist/**/*

cache:
  paths:
    - 'node_modules/**/*'
